export default {
    LOAD_LABTESTS_SUCCESS: "LOAD_LABTESTS_SUCCESS",
    CREATE_LABTESTS_SUCCESS: 'CREATE_LABTESTS_SUCCESS',
    UPDATE_LABTESTS_SUCCESS: 'UPDATE_LABTESTS_SUCCESS',
    DELETE_LABTESTS_SUCCESS: 'DELETE_LABTESTS_SUCCESS',

<<<<<<< HEAD
    LOAD_DIAGNOSTICCENTER_SUCCESS: "LOAD_DIAGNOSTICCENTER_SUCCESS",

    LOAD_HOMEREMEDIES_SUCCESS:"LOAD_HOMEREMEDIES_SUCCESS",


=======
>>>>>>> 1a1d9ede9cbb09034eaff46f55fa1971e529384e
    API_CALL: 'http://localhost:5002/'
}; 